Add prefer first or null rule
bancolombia/dart-code-linter pull request #150
Opened 2024-11-04 13:39 UTC by byshy

This PR has changes from [this PR](https://github.com/bancolombia/dart-code-linter/pull/149), please make sure to review that first

What's new?
- Adding a new rule that prefers the use of firstOrNull instead of first on iterables and its derivatives

2024-11-05 20:46 UTC, santitigaga requested changes

2024-11-05 20:46 UTC, santitigaga commented on test/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/examples/example.dart
> +// ignore_for_file: unnecessary_cast, unused_local_variable
please add desired result,  to show that it does not generate issue with `firstOrNull`

2024-11-05 20:46 UTC, santitigaga commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/prefer_first_or_null_rule.dart
> +  static const warningMessage = 'Use first instead of accessing the element at zero index or using first.';
Use firstorNull instead of accessing the element at zero index or using first.

2024-11-05 20:47 UTC, santitigaga commented
@byshy Amazing, this is a useful rule.
Please add this new rule in the documentation in the `gh-pages-source` branch

2024-11-06 06:53 UTC, byshy commented
I handled the comments above
I'm thinking about adding all the rules at once to the `gh-pages-source`, is that okay? or do you prefer to add them now?

2024-11-06 15:56 UTC, santitigaga commented
> I handled the comments above I'm thinking about adding all the rules at once to the `gh-pages-source`, is that okay? or do you prefer to add them now?

it's ok add all rules in one PR

2024-11-06 15:56 UTC, santitigaga approved these changes
Amazing !!!

2024-11-06 15:57 UTC, merged