Add fix command
bancolombia/dart-code-linter pull request #152
Opened 2024-11-04 13:59 UTC by byshy

Like the analyze command, I added a fix command that utilizes the replacement defined inside each rule to automatically replace the fixes

You can run the command on the example/lib and it will identify the 3 issues it has in the `main.dart` file, and fix only 1 (which has the replacement defined)
> dart run dart_code_linter:metrics fix example/lib

2024-11-06 16:00 UTC, santitigaga requested changes

2024-11-06 16:00 UTC, santitigaga commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_first_or_null/prefer_first_or_null_rule.dart
> +  static const warningMessage = 'Use first instead of accessing the element at zero index or using first.';
please pull the changes from trunk to merge this PR

2024-11-06 19:40 UTC, santitigaga commented
@byshy  please pull changes

2024-11-06 19:42 UTC, byshy commented
Done

2024-11-06 19:44 UTC, byshy commented
As a quick note, before publishing the changes to pub get, we should run the dart formatter on the changed files (in this PR and the 3 before) since I have custom rules on my IDE to set the length of the dart line to 130, it should be 80, so we should run that then publish

2024-11-06 20:19 UTC, santitigaga requested changes

2024-11-06 20:19 UTC, santitigaga commented on lib/src/cli/models/parsed_arguments.dart
> +        rootFolder: argResults[FlagNames.rootFolder] as String,
What do you think about keeping the jsonReportPath property?

2024-11-06 20:19 UTC, santitigaga commented on lib/src/cli/commands/fix_lints_command.dart
Is it easy for you to add tests?

2024-11-06 20:19 UTC, santitigaga commented on lib/src/cli/commands/fix_lints_command.dart
We need to document this too

2024-11-06 20:19 UTC, santitigaga commented on lib/src/analyzers/lint_analyzer/lint_analyzer.dart
> +        if (unit is ResolvedUnitResult) {
I think this is exactly the same as `runCliAnalysiso` only the message changes. What do you think about extracting this logic to a new function that receives the `message` _Fixing_ and  _Analyzing_ so as not to duplicate code?

2024-11-07 05:36 UTC, byshy commented on lib/src/cli/models/parsed_arguments.dart
> +        rootFolder: argResults[FlagNames.rootFolder] as String,
I removed it since the fix command already utilizes what the analyze do, so I thought no need for the report, we can keep it tho, I will add it

2024-11-07 05:37 UTC, byshy commented on lib/src/cli/commands/fix_lints_command.dart
Sure thing 🫡

2024-11-07 07:55 UTC, byshy commented on lib/src/cli/commands/fix_lints_command.dart
Will create a new PR for documenting all changes I made

2024-11-07 08:38 UTC, byshy commented
Notes handled, I'm available for new notes if any 🙏

2024-11-07 19:33 UTC, santitigaga approved these changes

2024-11-07 19:34 UTC, merged

2024-11-07 19:35 UTC, byshy commented
Amazing!!
Can we connect on linkedIn @santitigaga ?

2024-11-07 20:34 UTC, santitigaga commented
yes of course, https://linkedin.com/in/santiago-garcia-gil-742b38252/

2024-11-07 20:36 UTC, byshy commented
Invitation sent