Document changes from the last 4 PRs
bancolombia/dart-code-linter pull request #154
Opened 2024-11-08 16:54 UTC by byshy

- Add documentation for the fix command
- Add documentation for the no-blank-line-before-single-return rule
- Add documentation for the prefer-first-or-null rule
- Add documentation for the prefer-single-quotes rule

2024-11-08 19:31 UTC, santitigaga requested changes

2024-11-08 19:31 UTC, santitigaga commented on docs/rules/dart/prefer-first-or-null.mdx
> +added in: 1.6.1 <span style={{color: 'green'}}>style</span>
the new release will be 1.2.0 please

2024-11-08 19:31 UTC, santitigaga commented on docs/rules/dart/prefer-single-quotes.mdx
> +added in: 1.6.1 <span style={{color: 'green'}}>style</span>
the new release will be 1.2.0 please

2024-11-08 19:31 UTC, santitigaga commented on docs/rules/dart/no-blank-line-before-single-return.mdx
> +added in: 1.6.1 <span style={{color: 'green'}}>style</span>
the new release will be 1.2.0 please

2024-11-08 19:31 UTC, santitigaga commented on docs/cli/fix.md
> +
It would be helpful to add the version in which this task is added as well

2024-11-10 16:15 UTC, byshy commented
Will fix it shortly, just a quick note, after inspecting other files I saw the version 1.6.0, this is why I opted to using 1.6.1, do you want to check the other ones in another PR?

2024-11-11 03:04 UTC, santitigaga commented
@byshy  you are right, all rules are available since the first release, That version 1.6.0 is a bug that should have been left from the fork. At least adjust the contribution, I will adjust the others in the next few days.

2024-11-11 05:37 UTC, byshy commented
The version in the PR is fixed and the PR is ready

2024-11-12 02:21 UTC, santitigaga approved these changes
Thank you

2024-11-12 02:21 UTC, merged